//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "a3c012c7c20065de")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Master</summary>
	[PublishedContentModel("master")]
	public partial class Master : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "master";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Master(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Master, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Description: Maximum 160 characters
		///</summary>
		[ImplementPropertyType("MetaDescription")]
		public string MetaDescription
		{
			get { return this.GetPropertyValue<string>("MetaDescription"); }
		}

		///<summary>
		/// Meta Keywords: Maximum 10 keyword
		///</summary>
		[ImplementPropertyType("MetaKeywords")]
		public string MetaKeywords
		{
			get { return this.GetPropertyValue<string>("MetaKeywords"); }
		}

		///<summary>
		/// Page Title: Maximum 70 characters
		///</summary>
		[ImplementPropertyType("PageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("PageTitle"); }
		}

		///<summary>
		/// umbracoInternalRedirectId
		///</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public IPublishedContent UmbracoInternalRedirectId
		{
			get { return this.GetPropertyValue<IPublishedContent>("umbracoInternalRedirectId"); }
		}

		///<summary>
		/// UmbracoNaviHide
		///</summary>
		[ImplementPropertyType("UmbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("UmbracoNaviHide"); }
		}
	}

	/// <summary>About Us</summary>
	[PublishedContentModel("AboutUs")]
	public partial class AboutUs : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "AboutUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("Description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("Description"); }
		}

		///<summary>
		/// MyPhoto: Size of the photo: 480x360
		///</summary>
		[ImplementPropertyType("MyPhoto")]
		public string MyPhoto
		{
			get { return this.GetPropertyValue<string>("MyPhoto"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("Title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("Title"); }
		}
	}

	/// <summary>Contact Us</summary>
	[PublishedContentModel("ContactUs")]
	public partial class ContactUs : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ContactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("Address")]
		public IHtmlString Address
		{
			get { return this.GetPropertyValue<IHtmlString>("Address"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("Description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("Description"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("Email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("Email"); }
		}

		///<summary>
		/// Fax
		///</summary>
		[ImplementPropertyType("Fax")]
		public string Fax
		{
			get { return this.GetPropertyValue<string>("Fax"); }
		}

		///<summary>
		/// Mobile
		///</summary>
		[ImplementPropertyType("Mobile")]
		public string Mobile
		{
			get { return this.GetPropertyValue<string>("Mobile"); }
		}

		///<summary>
		/// Telephone
		///</summary>
		[ImplementPropertyType("Telephone")]
		public string Telephone
		{
			get { return this.GetPropertyValue<string>("Telephone"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("Title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("Title"); }
		}
	}

	/// <summary>Home Page</summary>
	[PublishedContentModel("HomePage")]
	public partial class HomePage : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "HomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Products</summary>
	[PublishedContentModel("Products")]
	public partial class Products : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Products";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Products(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Products, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Activate: If you need the data remain in cache memory, you can activate it.
		///</summary>
		[ImplementPropertyType("Activate")]
		public bool Activate
		{
			get { return this.GetPropertyValue<bool>("Activate"); }
		}

		///<summary>
		/// Time Valid: That shows how many seconds remaining data in cache memory.
		///</summary>
		[ImplementPropertyType("TimeValid")]
		public int TimeValid
		{
			get { return this.GetPropertyValue<int>("TimeValid"); }
		}
	}

	/// <summary>Product</summary>
	[PublishedContentModel("Product")]
	public partial class Product : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Product";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Product(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Product, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Author
		///</summary>
		[ImplementPropertyType("Author")]
		public string Author
		{
			get { return this.GetPropertyValue<string>("Author"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("Description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("Description"); }
		}

		///<summary>
		/// First Title
		///</summary>
		[ImplementPropertyType("FirstTitle")]
		public string FirstTitle
		{
			get { return this.GetPropertyValue<string>("FirstTitle"); }
		}

		///<summary>
		/// Icon
		///</summary>
		[ImplementPropertyType("Icon")]
		public string Icon
		{
			get { return this.GetPropertyValue<string>("Icon"); }
		}

		///<summary>
		/// Main Picture
		///</summary>
		[ImplementPropertyType("MainPicture")]
		public string MainPicture
		{
			get { return this.GetPropertyValue<string>("MainPicture"); }
		}

		///<summary>
		/// PictureForRelatedLinks: This picture will show for related links. Size: 250x150
		///</summary>
		[ImplementPropertyType("PictureForRelatedLinks")]
		public string PictureForRelatedLinks
		{
			get { return this.GetPropertyValue<string>("PictureForRelatedLinks"); }
		}

		///<summary>
		/// Price
		///</summary>
		[ImplementPropertyType("Price")]
		public string Price
		{
			get { return this.GetPropertyValue<string>("Price"); }
		}

		///<summary>
		/// Product Name
		///</summary>
		[ImplementPropertyType("ProductName")]
		public string ProductName
		{
			get { return this.GetPropertyValue<string>("ProductName"); }
		}

		///<summary>
		/// Related Links
		///</summary>
		[ImplementPropertyType("RelatedLinks")]
		public Umbraco.Web.Models.RelatedLinks RelatedLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("RelatedLinks"); }
		}

		///<summary>
		/// Second Title
		///</summary>
		[ImplementPropertyType("SecondTitle")]
		public string SecondTitle
		{
			get { return this.GetPropertyValue<string>("SecondTitle"); }
		}
	}

	/// <summary>Imprint</summary>
	[PublishedContentModel("Imprint")]
	public partial class Imprint : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Imprint";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Imprint(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Imprint, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Photo Collection</summary>
	[PublishedContentModel("PhotoCollection")]
	public partial class PhotoCollection : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "PhotoCollection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PhotoCollection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PhotoCollection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Photo</summary>
	[PublishedContentModel("Photo")]
	public partial class Photo : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Photo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Photo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Photo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("Description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("Description"); }
		}

		///<summary>
		/// Picture
		///</summary>
		[ImplementPropertyType("Picture")]
		public string Picture
		{
			get { return this.GetPropertyValue<string>("Picture"); }
		}
	}

	/// <summary>Highlight</summary>
	[PublishedContentModel("Highlight")]
	public partial class Highlight : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Highlight";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Highlight(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Highlight, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HighlightLinks
		///</summary>
		[ImplementPropertyType("HighlightLinks")]
		public Umbraco.Web.Models.RelatedLinks HighlightLinks
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("HighlightLinks"); }
		}
	}

	/// <summary>Banner Collection</summary>
	[PublishedContentModel("BannerCollection")]
	public partial class BannerCollection : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BannerCollection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BannerCollection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BannerCollection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Banner</summary>
	[PublishedContentModel("Banner")]
	public partial class Banner : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Banner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Banner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Banner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("Description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("Description"); }
		}
	}

	/// <summary>Incoming Calls</summary>
	[PublishedContentModel("IncomingCalls")]
	public partial class IncomingCalls : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "IncomingCalls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public IncomingCalls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<IncomingCalls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Incoming Call</summary>
	[PublishedContentModel("IncomingCall")]
	public partial class IncomingCall : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "IncomingCall";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public IncomingCall(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<IncomingCall, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contact Number
		///</summary>
		[ImplementPropertyType("ContactNumber")]
		public string ContactNumber
		{
			get { return this.GetPropertyValue<string>("ContactNumber"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("Email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("Email"); }
		}

		///<summary>
		/// FullName
		///</summary>
		[ImplementPropertyType("FullName")]
		public string FullName
		{
			get { return this.GetPropertyValue<string>("FullName"); }
		}

		///<summary>
		/// Reply
		///</summary>
		[ImplementPropertyType("Reply")]
		public IHtmlString Reply
		{
			get { return this.GetPropertyValue<IHtmlString>("Reply"); }
		}

		///<summary>
		/// SendReply
		///</summary>
		[ImplementPropertyType("SendReply")]
		public object SendReply
		{
			get { return this.GetPropertyValue("SendReply"); }
		}

		///<summary>
		/// Subject
		///</summary>
		[ImplementPropertyType("Subject")]
		public string Subject
		{
			get { return this.GetPropertyValue<string>("Subject"); }
		}

		///<summary>
		/// TextMessage
		///</summary>
		[ImplementPropertyType("TextMessage")]
		public IHtmlString TextMessage
		{
			get { return this.GetPropertyValue<IHtmlString>("TextMessage"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
